### ISSUE TITLE
Too many open files in RHEL

### ISSUE THREAD

**Issue by FPaquette** [medusa-project/cantaloupe#212]
Hi,

We are having a new issue since the beginning of the week, it happens a few times daily now. Here’s the error, have you seen this before? The error is happening when Cantaloupe is trying to access a web service to get the path to the image.

11:01:34.667 [http-nio-8080-exec-2]  [39mDEBUG [0;39m  [36me.i.l.c.c.InfoService [0;39m - getInfo(): retrieved info of 9dbhchGkD6BTpDp36s8dsw from ObjectCache
DELEGATE : Executing self.authorized delegate
Get access (restrictions) info from service : service_base_uri=http://vpldsb.bnquebec.ca/get-bitstream-path
identifier :9dbhchGkD6BTpDp36s8dsw
client_ip :70.80.101.84
client_ip_from_headers :70.80.101.84
request uri: http://vpldsb.bnquebec.ca/get-bitstream-path?ebsid=9dbhchGkD6BTpDp36s8dsw&ip=70.80.101.84
Get access (restrictions) info from service : service_base_uri=http://vpldsb.bnquebec.ca/get-bitstream-path
Errno::EMFILE: Too many open files - Failed to open TCP connection to vpldsb.bnquebec.ca:80 (Too many open files - Too many open files)
        initialize at org/jruby/ext/socket/RubyTCPSocket.java:147
              open at org/jruby/RubyIO.java:1154
  block in connect at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:885
           timeout at org/jruby/ext/timeout/Timeout.java:149
           connect at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:883
          do_start at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:868
             start at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:857
           request at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1409
       authorized? at <script>:73
11:01:34.672 [http-nio-8080-exec-2]  [1;31mERROR [0;39m  [36mo.r.C.RestletApplication [0;39m - Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
	at org.restlet.resource.ServerResource.get(ServerResource.java:723)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:662)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1020)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.script.ScriptException: org.jruby.embed.InvokeFailedException: (EMFILE) Too many open files - Failed to open TCP connection to vpldsb.bnquebec.ca:80 (Too many open files - Too many open files)
	at org.jruby.embed.jsr223.JRubyEngine.wrapException(JRubyEngine.java:104)
	at org.jruby.embed.jsr223.JRubyEngine.invokeMethod(JRubyEngine.java:220)
	at edu.illinois.library.cantaloupe.script.RubyScriptEngine.doInvoke(RubyScriptEngine.java:157)
	at edu.illinois.library.cantaloupe.script.RubyScriptEngine.invoke(RubyScriptEngine.java:115)
	at edu.illinois.library.cantaloupe.auth.Authorizer.authorize(Authorizer.java:82)
	at edu.illinois.library.cantaloupe.resource.AbstractResource.checkAuthorization(AbstractResource.java:234)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGet(ImageResource.java:138)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
	... 61 common frames omitted
Caused by: org.jruby.embed.InvokeFailedException: (EMFILE) Too many open files - Failed to open TCP connection to vpldsb.bnquebec.ca:80 (Too many open files - Too many open files)
	at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.call(EmbedRubyObjectAdapterImpl.java:320)
	at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callMethod(EmbedRubyObjectAdapterImpl.java:170)
	at org.jruby.embed.ScriptingContainer.callMethod(ScriptingContainer.java:1475)
	at org.jruby.embed.jsr223.JRubyEngine.invokeMethod(JRubyEngine.java:215)
	... 70 common frames omitted
Caused by: org.jruby.exceptions.RaiseException: (EMFILE) Too many open files - Failed to open TCP connection to vpldsb.bnquebec.ca:80 (Too many open files - Too many open files)
	at org.jruby.ext.socket.RubyTCPSocket.initialize(org/jruby/ext/socket/RubyTCPSocket.java:147)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1154)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.block in connect(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:885)
	at org.jruby.ext.timeout.Timeout.timeout(org/jruby/ext/timeout/Timeout.java:149)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.connect(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:883)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.do_start(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:868)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.start(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:857)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.net.http.request(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1409)
	at $_lt_script_gt_.authorized?(<script>:73)
12-Apr-2018 11:01:34.674 SEVERE [http-nio-8080-Acceptor-0] org.apache.tomcat.util.net.NioEndpoint$Acceptor.run Socket accept failed
 java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:455)
	at java.lang.Thread.run(Thread.java:748)

The ulimit for the user running the application server is up to 1,000,000 and when the problem happens, there are about 250,000 files open. I’m not sure why of its normal to have that many, what do you think?

Thanks!

**Comment by adolski** [comment]
Definitely not normal... Looks like the error is coming from Net::HTTP? But why would Net::HTTP be opening files? Maybe it's opening sockets and not closing them? Does `lsof` reveal anything interesting?

**Comment by FPaquette** [comment]
This is the dump that I got the last time it crashed a bit earlier today. We can see all the files still open in the cache.

https://www.dropbox.com/s/sqaq3cbulobu04f/pvlimg0a-dump.txt?dl=0

I tried adding the method 'finish' to the http call in delegates.rb but it's throwing an error saying the connection is not open.  I'm seeing in your example that you do not use it so I'm guessing it is not mandatory?

https://medusa-project.github.io/cantaloupe/manual/3.4/delegate-script.html

 def self.authorized?(identifier, full_size, operations, resulting_size,
                       output_format, request_uri, request_headers, client_ip,
                       cookies)

    puts "DELEGATE : Executing self.authorized delegate"

    service_base_uri = 'http://vpldsb.bnquebec.ca/get-bitstream-path'
    puts "Get access (restrictions) info from service : service_base_uri=" + service_base_uri


    client_ip_from_headers = CGI.escape(request_headers["x-forwarded-for"])
    puts "identifier :" +  identifier
    puts "client_ip :" + client_ip
    puts "client_ip_from_headers :" + client_ip_from_headers

    uri = service_base_uri + '?ebsid=' + CGI.escape(identifier) + '&ip=' + CGI.escape(client_ip_from_headers)
    puts "request uri: " + uri 

    puts "Get access (restrictions) info from service : service_base_uri=" + service_base_uri

    uri = URI.parse(uri)

    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)
    
    response = http.request(request)

**Comment by adolski** [comment]
I think you found it... let me see if I can figure out why there are so many open cache files.

**Comment by eric-gagnon** [comment]
Hello,

Hope you are going well! I'm giving a little bit of help to François investigating the issue.

I have the impression that it could be unclosed request (I have tried to get the currrent request count on Rhel system but I was not able to find the adequate command (i tried with cat /proc/net/sockstat{,6} but it doesnt look like the request count stays up, but maybe the measurement is wrong).

What it is sure is that there is a leak in file openened. I was able to reproduce it with my 10 images open test case (going from 15k lsof lines to 250k and the getting the error in ruby).

To isolate the issue I changed the test to open only one file and waited a bit after (I think tcp connection could hold for 2 minutes, not sure what the current configs are). I get something like 50 files leak at each image request (for the same image).

My test:
- restart server (tomcat integration)
- take a lsof snapshop
- load image
- take a few lsof, wait for a time
- load a new image
- take lsof after a time

I diff on the two files, it's not easy to look at because there is no timestamp but I do see that I have a few reference to file in cache (I tough first that could have been a map object keeping  track of cache file by id but I guess that where would be reference then).

You can see it in the pic (same id) 

![isolate](https://user-images.githubusercontent.com/21067311/38699463-1aae559e-3e66-11e8-83ef-d764844b64e6.png)

I have tried changing the ruby script to use **start** instead of **new** but it does look like not fixing the issue (from ruby doc : When this method is called with a block, it passes the Net::HTTP object to the block, and closes the TCP connection and HTTP session after the block has been executed.).

Any suggestion of things I could do to help isolate the issue? I'm not officially on the project otherwise I would surely try to reproduce it locally.

**Comment by eric-gagnon** [comment]
I did the test again but for only one request using Chrome (restart server, one request, lsof), I get 50 file open of the image in cache.

**Comment by eric-gagnon** [comment]
For the scripts, we use the file system resolver and authorize but they are very similar in implementation as the same service is used to get the access right and path of file and it's close to documentation sample (this is the version with **start** instead of **new** for http)


Exemple

    def self.get_pathname(identifier, context)
        uri = 'http://ourserver/ourservice?imageidentifier=' + CGI.escape(identifier)
        uri = URI.parse(uri)

        http = Net::HTTP.start(uri.host, uri.port)
        request = Net::HTTP::Get.new(uri.request_uri)
        response = http.request(request)
        return nil if response.code.to_i >= 400

        doc = REXML::Document.new(response.body)
        path = (REXML::XPath.match( doc, "/root/bitstream/path/text()" )).to_s
        path.nil? ? nil : path[2..path.length - 3]
     end

**Comment by eric-gagnon** [comment]
Oh, I think I got it, I had misread the documentation, we need to use code block.
I have tried this version and it seem to fix the leak. I will try some more and report

        response = nil
        http = Net::HTTP.new(uri.host, uri.port) do |http, response|
                request = Net::HTTP::Get.new(uri.request_uri)
                response = http.request(request)
        end

**Comment by adolski** [comment]
Thanks for looking into this, @eric-gagnon.

I'm not sure what's happening here. `lsof` says the files are open for reading, so presumably they have already been written and are being read again during a later request. (?) The symptom of 50 new open files for a single request sounds very bizarre to me. I wonder what open files these are and where they coming from? Are they 50 handles on the same file or 50 different files?

I don't know if Net::HTTP is involved in this problem. Maybe it is, but is may just be raising errors that relate to a leak happening somewhere else. The fact that there are so many open cache files suggests that the problem lies somewhere in the code paths that are responsible for opening & closing cached derivative images for reading. But I don't see any leaks there... although, feel free to double-check me:

-----

Here is the FilesystemCache method that opens an InputStream for reading a cache file:

https://github.com/medusa-project/cantaloupe/blob/17ea2a47a60b160efbdc116051e95ca2524aa04b/src/main/java/edu/illinois/library/cantaloupe/cache/FilesystemCache.java#L693-L712

The only place it's called is in:

https://github.com/medusa-project/cantaloupe/blob/17ea2a47a60b160efbdc116051e95ca2524aa04b/src/main/java/edu/illinois/library/cantaloupe/cache/CacheFacade.java#L92-L99

which, when `cache.server.resolve_first = true`, is called by

https://github.com/medusa-project/cantaloupe/blob/17ea2a47a60b160efbdc116051e95ca2524aa04b/src/main/java/edu/illinois/library/cantaloupe/resource/ImageRepresentation.java#L82-L83

Or, when `cache.server.resolve_first = false`, is called by

https://github.com/medusa-project/cantaloupe/blob/17ea2a47a60b160efbdc116051e95ca2524aa04b/src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v2/ImageResource.java#L88

------

In a quick test with version 3.4.2 with FilesystemCache in macOS + Java 10, `lsof` doesn't report any open cache files for me.

------

One thing to try would be to start an instance with as close to a default configuration as possible. See if that leaks. Change some stuff, see if that leaks, etc.

**Comment by eric-gagnon** [comment]
Sorry the ruby fix is not right, I had the browser cache enabled.

**Comment by eric-gagnon** [comment]
"Are they 50 handles on the same file or 50 different files?"
Same path so I guess same file...

**Comment by eric-gagnon** [comment]
Not sure if this can be usefull, for my isolated test (one image) the thread id (Tid) seem to be different for each file open. Could it be related to streaming?

File descriptor is always the same (202r) (r for read, not sure what 202 value is exactly)

**Comment by adolski** [comment]
> Not sure about ruby too but my coworker had found reference invoving a similar pattern, like you can see here : https://www.ruby-forum.com/topic/213887

Interesting find. A different HTTP client might be another thing to try...

**Comment by eric-gagnon** [comment]
I did the test.

1) Removed the autorized code to return true (so no http call there)
2) fileresolver delegated http call is not called because images are comming from the cache.

The issue can still be reproduced.

I'll wait for François before going further, looks like dev is running 3.3.2, I think we should definitively try with latest, sorry for not thinking about it.

**Comment by eric-gagnon** [comment]
Actually I think it's the latest but got confused by old config files, I will double check that.

**Comment by eric-gagnon** [comment]
OK, so I did a standalone test. I use a copy of our server so everything is the same otherwiser (on Rhel 7 server).

I stopped Tomcat and Apache and started Cantaloupe standalone (running under root).

(same configs as our other server except change to use port 80 and 443)
sudo java -Dcantaloupe.config=cantaloupe_eric_test.properties -Xmx2g -jar Cantaloupe-3.4.war

I took lsof measurement after Cantaloupe was started.
Loaded 1 image and took a new measure and another one after a long time and another one while typing this.

Cache was primed, so it is a test with image returned from derivative cache

12:12:22.047 [qtp654582261-17] DEBUG e.i.l.c.r.AbstractResource - Public identifier requested: 7WblShr2E6fB8Krtr-WNeA -> decoded: 7WblShr2E6fB8Krtr-WNeA -> slashes substituted: 7WblShr2E6fB8Krtr-WNeA | X-IIIF-ID header: null
12:12:22.048 [qtp654582261-17] DEBUG e.i.l.c.r.AbstractResource - Base URI assembled from request: http://dvlimg0b.bnquebec.ca
12:12:22.062 [qtp654582261-17] DEBUG e.i.l.c.r.CachedImageRepresentation - Streamed from the cache without resolving in 3 msec

The socket and ref to cache was open after a time 

java      6341 6343           root  138u     IPv6              77002       0t0        TCP *:http (LISTEN)
java      6341 6343           root  139u     unix 0xffff88003667e000       0t0      77003 socket
java      6341 6343           root  140r     FIFO                0,8       0t0      77005 pipe
java      6341 6343           root  141w     FIFO                0,8       0t0      77005 pipe
java      6341 6343           root  142u  a_inode                0,9         0       5901 [eventpoll]
java      6341 6343           root  146r      REG              253,4      2449   16896954 /var/cantaloupe/cache/image/76/f5/f3/76f5f383c79d0dd29d1adf5c78bc431a_2b1eb264a09d2d10c7b39b87a2bea88d.jpg
java      6341 6344           root  cwd       DIR              253,5      4096    1015798 /opt/Cantaloupe-3.4

But with my last lsof it's not there anymore.

It does look like Tomcat is not doing it's job or holding on socket / ressource for longer than it needs.

I will be doing a few more test after lunch to make sure I can reproduce this (and also do it with more images  and no cache).

**Comment by eric-gagnon** [comment]
Well, I was actually able to crash standalone version too, just by doing a multiple reload of my 10 images page test.

12:35:27.421 [qtp654582261-33] ERROR o.r.C.RestletApplication - /var/cantaloupe/cache/image/b7/8d/c2/b78dc2593cde9b85613c92a321b05f83_2b1eb264a09d2d10c7b39b87a2bea88d.jpg: Too many open files
2018-04-13 12:35:27.421:WARN:oejs.HttpChannel:qtp654582261-28: /iiif/2/o7iYXMQbssxGH-E38dlpVA/full/140,/0/default.jpg
java.lang.NoClassDefFoundError: edu/illinois/library/cantaloupe/operation/ValidationException
        at edu.illinois.library.cantaloupe.RestletApplication$CustomStatusService.toStatus(RestletApplication.java:100)
        at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:142)
        at org.restlet.routing.Filter.handle(Filter.java:197)

**Comment by FPaquette** [comment]
Just to let you know that we have found a workaround, here's the solution in case anybody needs it. This is working on RHEL 7.4

1. Modify the value for the ulimit for the user tomcat.
/etc/security/limits.conf
tomcat           soft    nofile          1024000 
tomcat           hard    nofile          1024000

2. Modify the value in the tomcat.service at startup
/etc/systemd/system
LimitNOFILE=1024000

If you modify the first one only, it won't work.

I created a script to help monitoring the amount of files that are open and the server was up to 913,00 this weekend. Before the changes, it crashed at about 240,000.

I'll test your ideas when I have a bit of free time.

**Comment by FPaquette** [comment]
I'm able to replicate the issue or at least, see the files being open. Here are the tests I did using Cantaloupe 3.4 with Java 8.

1.  Using the standalone version, without delegates and cache : it's fine

2. Using the standalone version, without delegates, with cache : it's fine

3. Using Tomcat, without delegates and cache : it's fine.

4. Using Tomcat, without delegates, with cache : I can see the files. It doesn't happen everything, about 1/5 I'll say.  There is quite a lot, 40 overall for one request. Here's an example, they all have the same path and name.

java      24521 24590         tomcat   61r      REG              253,4      2300   33597292 /var/cantaloupe/cache/image/e3/af/52/e3af525aecc708dee68015d4f6a25356_00ac903e491a2f5e99aaba40c2a4001b.jpg

I tested again the standalone version after that and I wasn't able to get it. I'll do more tests juste to be sure and get back to you.

**Comment by FPaquette** [comment]
I upgraded to Java 9 and Tomcat 9 and I'm seeing the same issue.

**Comment by adolski** [comment]
@FPaquette Do you have any info about this Tomcat flaw?

**Comment by FPaquette** [comment]
Not much beside people were talking about it back in 2005. I'll see if I can find something useful.

**Comment by eric-gagnon** [comment]
Hello,

On my side I have left the investigation aside, it's really François that is responsible of the server in our organisation, I just wanted to give a little help.

I have lost my computer a few weeks ago and my setup to debug otherwise I would surely trace the request more closely. Like I said before I was able to see the issue with standalone version but I have not tested without delegate like François did. I would surely have digged that further.

But I retough about it a bit and I think one of the thing that could help me repeat the issue more rapidly is that I was actually reloading the page without waiting for the page to load completely. I wonder if there could be a problem with the handling of cut / dropped request (but in the other hand it's probably not that common in our production environnement).

**Comment by filak** [comment]
The symptoms feel familiar, are the libraries/components involved in the process threadsafe?

**Comment by adolski** [comment]
I don't want to log into your server, but so far I've checked the cache file access on the following platforms:

* macOS, Oracle JDK 8u161, Cantaloupe 3.4.2, standalone
* macOS, Oracle JDK 10, Cantaloupe 3.4.2, standalone
* Ubuntu, Oracle JDK 9.0.1, Cantaloupe 3.4.2, standalone
* Ubuntu, Oracle JDK 9.0.1, Cantaloupe 3.4.2, Tomcat 9.0.7

It works as expected, with `lsof` reporting nothing when no files are open, a bunch of write handles while a file is writing, and then nothing again after it's closed. It also reports nothing after a connection is prematurely closed while an image is being written to the response & cache.

So, it could be that none of these platforms are affected, or it could be that I'm not going through the right steps to trigger it.

Note that FilesystemCache is probably the most used cache, and most users are fine with their OS's default ulimit of 1024 or something small like that. I can't help but suspect that something about your setup is unique. I'm happy to look into this further but so far I haven't had any success reproducing it on my end.

**Comment by FPaquette** [comment]
It could be something with our setup. I'll give it a try using Ubuntu and get back to you. Thanks!

**Comment by FPaquette** [comment]
It's fine using Ubuntu :

- Ubuntu 18.04, Java 8u162, Cantaloupe 3.4.2, standalone
- Ubuntu 18.04, Java 8u162, Cantaloupe 3.4.2, Tomcat 8.5.32 

But I'm seeing the issue with CentOS 7.4 as with RHEL. It looks like there is something with this platform.

Is there anything else you would want me to test that could useful to you?

**Comment by adolski** [comment]
In the other part of my job, up until about 6 months ago, we were using FilesystemCache in two VMs running RHEL 7.3. We ran Cantaloupe (< 3.4) in standalone mode behind an nginx reverse proxy with the default ulimit (1024), and never encountered this. But we stopped using FilesystemCache for other reasons.

I think the variables we're looking at (OS, JVM, container) are too broad and the problem is probably more specific. I hate to blame a whole OS.

Do you think it would be possible to package up a demonstration of this issue into a Docker container or VM image?

**Comment by FPaquette** [comment]
Sure, I'll get back to you.

**Comment by FPaquette** [comment]
Is a VMDK from WMware fine for you?

**Comment by adolski** [comment]
That's fine

**Comment by FPaquette** [comment]
Sorry about the late reply.  It looks like the issue could be related to version 7.4 because I'm not seeing it if I upgrade to 7.5.  291 libraries were updated so it's hard to say which one was causing the issue.

Do you still want a VMDK? I have rebuild a server using as little space as possible for you.

**Comment by adolski** [comment]
Hi @FPaquette,

It would be interesting to find out exactly what was going on, but I think if you're satisfied that it's fixed, then that's good enough for me. Maybe the OS or some library really was at fault...

**Comment by FPaquette** [comment]
I'll send you an email with a link to our ftp server in a few minutes.

**Comment by adolski** [comment]
Just found this in case it may help: http://file-leak-detector.kohsuke.org

**Comment by FPaquette** [comment]
I was (finally) going to try the file-leak-detector tool and for some reason, I wasn't seeing the problem. After looking at my logs, upgrading from 3.4 to 3.4.4 fixed it. Everything is back to normal.  

I'm looking at the all the fixes from 3.4 to 3.4.4 and I can't really tell which one would have be helpfull. 

That said, I guess we can close this issue now. Unless you would like to me to downgrade to 3.4 and run the tool?

**Comment by adolski** [comment]
Hi @FPaquette,

It's good news that this issue seems to finally be resolved, but I also can't tell what changed between 3.4 and 3.4.4 to fix it.

I will go ahead and close it then, since I've never been able to reproduce it myself, and I can't take any action until that changes. It can always be reopened.

Thanks for all of your investigative efforts!
